
---
 
- name: Restoration the BIGIPs to default with just management IP
  hosts: bigips
  gather_facts: no
  connection: local
 
  environment:
    F5_SERVER: "{{ ansible_host }}"
    F5_USER: "admin"
    F5_PASSWORD: "admin"
    F5_VALIDATE_CERTS: no
 
  tasks:
    - name: Reset the BIG-IP configuration
      bigip_config:
        reset: yes
        save: yes
 
    - name: Delete bigip.license file
      bigip_raw:
       commands: rm -rf /config/bigip.license
 
 
    - name: Reboot the BIGIP after restoration of UCS
      bigip_command:
        commands: tmsh reboot
      ignore_errors: True
 
 
    - name: Waiting for BIGIP to finish rebooting
      pause:
        seconds: 90
 
 
    - name: Wait for BIGIP to be actually ready
      bigip_wait:

